### ISSUE TITLE
Spark-Ext Gather Function doesn't work with Spark 1.6

### ISSUE THREAD

**Issue by rlgarris** [collectivemedia/spark-ext#16]
Error: java.lang.NoClassDefFoundError: org/apache/spark/sql/catalyst/expressions/PartialAggregate1

**Comment by lapolonio** [comment]
+1

**Comment by rlgarris** [comment]
The code is using a private API, which has been removed from Spark 1.6. Please update your code.

**Comment by gianvi** [comment]
Some news for this problem? Thanks
